### ISSUE TITLE
HP+ auto upgrade failure

### ISSUE THREAD

**Issue by samrose** [Holo-Host/issue-tracker#11]
Expected behavior:

hpos will autoupgrade on schedule on holoport+ after initial update

Actual behavior
![IMG_0276](https://user-images.githubusercontent.com/115821/71752345-b9557880-2e4c-11ea-8d08-7fd856b3b381.JPG)

**Comment by samrose** [comment]
@yegortimoshenko it appears that the script on this machine is trying to find `/dev/sda` although the HDD in this case is `/dev/sdc`

**Comment by yegortimoshenko** [comment]
Thank you for a good bug report. Is this with or without USB flash drive inserted in HP+? Does that alleviate the issue?

**Comment by yegortimoshenko** [comment]
I'm pretty worried about how exactly we're going to fix this :(

**Comment by yegortimoshenko** [comment]
Could you send `ls -ahl /dev/disk/by-uuid` output from several HoloPorts?

**Comment by samrose** [comment]
I did follow up and help @yegortimoshenko with this over the weekend. It resulted in a fix that appears to have resolved issues for HP+ customers

**Comment by paulbhartzog-holo** [comment]
Confirmed: auto-upgrade service fixes the problem.  User still has to find a way to boot in order to trigger auto-upgrade, but I did that, and it worked.
