### ISSUE TITLE
Flashing Purple LED interrupts Aurora LED for 1/2 sec sometimes

### ISSUE THREAD

**Issue by samrose** [Holo-Host/issue-tracker#14]
@yegortimoshenko mentioned that the timeout can be refined to try and prevent this

**Comment by yegortimoshenko** [comment]
Yup, essentially currently we are establishing a TCP connection literally every second, and if it takes more than one second to establish, we fall back to flashing purple: https://github.com/Holo-Host/holo-nixpkgs/blob/4627fc77bab98a13574bb34e1fbb9e72c7efdb2b/overlays/holo-nixpkgs/hpos-led-manager/src/main.rs#L48

**Comment by yegortimoshenko** [comment]
Needless to say, this is not a very adequate way of telling whether someone is online or not.

**Comment by samrose** [comment]
I left a comment that we shouldn't probably escalate issues based on 1/2 second or very short interval flashing purple lights. And, we should have very good front line customer support diagnosis to assure we have determined the problem is not the ISP network connection, or hardware related to network first, before escalation.

Very short network connection issues are to be expected. The purple light is just an awareness of that state. Practically all participants in holo will experience intermittent connection

**Comment by samrose** [comment]
closing this one, we could open an issue in holo-nixpkgs to refine the purple flashing behavior
